# MYSQL config
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_shop_db?serverTimezone=UTC&useLegacyDatetimeCode=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# H2 config
spring.h2.console.enabled=true
spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:h2:mem:test_mem
spring.datasource.username=sa
spring.datasource.password=

regex.email="(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])")